obstacle_range: 4.0
raytrace_range: 5.0
footprint: [[-0.9, -0.42], [-0.9, 0.42], [0.9, 0.42], [0.9, -0.42]]
inflation_radius: 0.5
cost_scaling_factor: 1.1

observation_sources: laser_scan_sensor #point_cloud_sensor

map_type: costmap
observation_sources: scan
scan: {sensor_frame: velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true}
