obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.4, -0.42], [-0.4, 0.42], [0.4, 0.42], [0.4, -0.42]]
inflation_radius: 0.15
cost_scaling_factor: 3.0

observation_sources: laser_scan_sensor #point_cloud_sensor

map_type: costmap
observation_sources: scan
scan: {sensor_frame: velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true}
