# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.5
  lethal_cost_threshold: 72

  resolution: 0.05
  static_map: true
  width: 12.0
  height: 12.0

 
